language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

install:
  - composer require jakub-onderka/php-parallel-lint

script:
  - vendor/bin/parallel-lint --exclude vendor .


